// Copyright 2013 Google Inc. All Rights Reserved.

/**
 * @author Jason Ganetsky (ganetsky@google.com)
 * @fileoverview This encapsulates data about a DCP failure from core. It is
 * generated by CommandBase, and passed through to CommandQueueManager.
 */
define([
    'qowtRoot/utils/typeUtils'
  ], function(
    TypeUtils) {

  'use strict';

  var _factory = {
    /**
     * Returns whether obj was created by CoreFailure.create.
     */
    isInstance: function(obj) {
      return _type.isOfType(obj);
    },

    /**
     * Creates a new CoreFailure object, and copies the properties from obj.
     * @param obj.error {Object} the object representing an error.
     * @param obj.errorPolicy {Object} policy or handling the error, including
     *     ignoreError.
     */
    create: function(obj) {
      var sealedObj = {
        error: undefined,
        errorPolicy: undefined
      };

      _type.markAsType(sealedObj);

      // Cause an exception to be thrown whenever someone misspells the name
      // of a property.
      Object.seal(sealedObj);

      for (var i in obj) {
        sealedObj[i] = obj[i];
      }

      return sealedObj;
    }
  };

  var _type = TypeUtils.createNewType('coreFailure');
  return _factory;
});
