define([
  'qowtRoot/commands/common/deleteQowtElement',
  'qowtRoot/commands/common/formatQowtElement',
  'qowtRoot/commands/common/moveQowtElement',
  'qowtRoot/commands/text/addQowtCharacterRun',
  'qowtRoot/commands/text/addQowtField',
  'qowtRoot/commands/text/addQowtHyperlink',
  'qowtRoot/commands/text/addQowtLineBreak',
  'qowtRoot/commands/text/addQowtPageBreak',
  'qowtRoot/commands/text/addQowtParagraph',
  'qowtRoot/commands/text/addQowtFooter',
  'qowtRoot/commands/text/addQowtFooterItem',
  'qowtRoot/commands/text/addQowtHeader',
  'qowtRoot/commands/text/addQowtHeaderItem',
  'qowtRoot/commands/text/addQowtSection',
  'qowtRoot/commands/text/addQowtTable',
  'qowtRoot/commands/text/addQowtTableCell',
  'qowtRoot/commands/text/addQowtTableRow',
  'qowtRoot/commands/text/breakRun',
  'qowtRoot/commands/text/deleteQowtText',
  'qowtRoot/commands/text/insertQowtText',
  'qowtRoot/commands/text/addQowtColumnBreak'], function(
  DeleteQowtElementCmd,
  FormatQowtElementCmd,
  MoveQowtElementCmd,
  AddQowtCharRunCmd,
  AddQowtFieldCmd,
  AddQowtHyperlinkCmd,
  AddQowtLineBreakCmd,
  AddQowtPageBreakCmd,
  AddQowtParagraphCmd,
  AddQowtFooterCmd,
  AddQowtFooterItemCmd,
  AddQowtHeaderCmd,
  AddQowtHeaderItemCmd,
  AddQowtSectionCmd,
  AddQowtTableCmd,
  AddQowtTableCellCmd,
  AddQowtTableRowCmd,
  BreakRunCmd,
  DeleteQowtTextCmd,
  InsertQowtTextCmd,
  AddQowtColumnBreakCmd) {

  'use strict';

  return {
    addQowtCharRun: AddQowtCharRunCmd,
    addQowtField: AddQowtFieldCmd,
    addQowtHyperlink: AddQowtHyperlinkCmd,
    addQowtLineBreak: AddQowtLineBreakCmd,
    addQowtPageBreak: AddQowtPageBreakCmd,
    addQowtParagraph: AddQowtParagraphCmd,
    addQowtFooter: AddQowtFooterCmd,
    addQowtFooterItem: AddQowtFooterItemCmd,
    addQowtHeader: AddQowtHeaderCmd,
    addQowtHeaderItem: AddQowtHeaderItemCmd,
    addQowtSection: AddQowtSectionCmd,
    addQowtTable: AddQowtTableCmd,
    addQowtTableCell: AddQowtTableCellCmd,
    addQowtTableRow: AddQowtTableRowCmd,
    breakRun: BreakRunCmd,
    deleteQowtElement: DeleteQowtElementCmd,
    deleteQowtText: DeleteQowtTextCmd,
    format: FormatQowtElementCmd,
    formatQowtElement: FormatQowtElementCmd,
    insertQowtText: InsertQowtTextCmd,
    moveQowtElement: MoveQowtElementCmd,
    addQowtColumnBreak: AddQowtColumnBreakCmd
  };

});
